[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymccanalysis"
version = "1.0.0"
description = "Analysis of PTW Array and Water Tank data"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "James Murphy", email = "you@example.com" }
]
keywords = ["medical", "physics", "analysis", "ptw", "water tank", "pdds", "profiles"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    # "requests>=2.32",
    "matplotlib==3.10.9",
    "numpy==2.4.5",
    "pydicom>=2.4.5",
    "pylinac>=3.43.2",
    "pymedphys>=0.41.0",
    "scikit-image==0.26.0",
    "scipy==1.17.1",
    "types-pytz>=2022.1.1"
]

[project.urls]
Homepage = "https://https://github.com/bobred/pymccanalysis"
Repository = "https://https://github.com/bobred/pymccanalysis"

[tool.setuptools.packages.find]
where = ["."]
include = ["pymccanalysis*"]
exclude = ["pymccanalysis.examples*"]